doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                    MATCH: App\Generales\MatchAgainst
                    SOUNDEX: App\Generales\Soundex
                    date: DoctrineExtensions\Query\Mysql\Date
                    current_date: DoctrineExtensions\Query\Mysql\CurrentDate
                    date_format: DoctrineExtensions\Query\Mysql\DateFormat
                    timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                    datediff: DoctrineExtensions\Query\Mysql\DateDiff
                    month: DoctrineExtensions\Query\Mysql\Month
                    day: DoctrineExtensions\Query\Mysql\Day
                    year: DoctrineExtensions\Query\Mysql\Year
                    round: DoctrineExtensions\Query\Mysql\Round
                    IF: DoctrineExtensions\Query\Mysql\IfElse

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
