monolog:
    channels: [doctrine_channel]
    handlers:

        main:
            channels: ["!event", "!doctrine_channel"]
        db_handler:
                # The level of the handler is configured at the same service level: https://github.com/symfony/monolog-bundle/issues/116
                type: service
                id: monolog.db_handler
                channels: ["!event", "!doctrine", "!console"]

when@dev:
    monolog:
        channels: [doctrine_channel]
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!doctrine_channel"]
            db_handler:
                # The level of the handler is configured at the same service level: https://github.com/symfony/monolog-bundle/issues/116
                type: service
                id: monolog.db_handler
                channels: ["!event", "!doctrine", "!console"]
                
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                excluded_404s:
                    # regex: exclude all 404 errors from the logs
                    - ^/
                handler: db_handler
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            deprecation_filter:
                type: filter
                handler: deprecation
                max_level: info
                channels: ["php"]
            db_handler:
                # The level of the handler is configured at the same service level: https://github.com/symfony/monolog-bundle/issues/116
                type: service
                id: monolog.db_handler
                channels: ["!event", "!doctrine", "!console"]
            rotating:
                type:  rotating_file
                path:  '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                # max number of log files to keep
                # defaults to zero, which means infinite files
                max_files: 5
